//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Token
    {
        public long User_ID { get; set; }
        public long Mall_ID { get; set; }
        public string Access_Token1 { get; set; }
        public long Expirse_In { get; set; }
        public string Refresh_Token { get; set; }
        public long RExpirse_In { get; set; }
    }
}
