//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Role
    {
        public int id { get; set; }
        public string role_name { get; set; }
        public int create_uid { get; set; }
        public long create_date { get; set; }
        public int shop_id { get; set; }
        public string description { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<bool> system_role { get; set; }
    }
}
