//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Action
    {
        public int id { get; set; }
        public string action_name { get; set; }
        public string action_description { get; set; }
        public bool enable { get; set; }
        public string action_description1 { get; set; }
    }
}
