//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Back_Stock
    {
        public long Back_Sock_ID { get; set; }
        public long Back_Date { get; set; }
        public long Shop_ID { get; set; }
        public long StoreHouse_ID { get; set; }
        public long User_ID { get; set; }
        public string Description { get; set; }
        public long Back_Sale_ID { get; set; }
    }
}
