//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Feature { get; set; }
        public Nullable<int> Function { get; set; }
        public string Description { get; set; }
        public long Created { get; set; }
        public int Created_By { get; set; }
        public int Status { get; set; }
        public Nullable<long> Modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<int> Resolved_By { get; set; }
        public Nullable<long> Resolved { get; set; }
    }
}
