//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug_Response
    {
        public int ID { get; set; }
        public int BugID { get; set; }
        public string Description { get; set; }
        public long Created { get; set; }
        public int Create_By { get; set; }
    }
}
