//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_Order
    {
        public int Buy_Order_ID { get; set; }
        public int Supplier_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<long> Write_Date { get; set; }
        public Nullable<long> Insure_Date { get; set; }
        public Nullable<long> End_Date { get; set; }
        public long Create_Date { get; set; }
        public int Shop_ID { get; set; }
        public Nullable<int> Order_User_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
    }
}
