//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_Detail
    {
        public long Buy_ID { get; set; }
        public long Product_ID { get; set; }
        public long Buy_Order_ID { get; set; }
        public long Quantity { get; set; }
        public decimal Price { get; set; }
        public long Create_Date { get; set; }
    }
}
