//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_Price_Detail
    {
        public int Buy_Price_ID { get; set; }
        public int Supplier_ID { get; set; }
        public int Parent_Product_ID { get; set; }
        public int Product_ID { get; set; }
        public double Price { get; set; }
        public int PricedUser_ID { get; set; }
        public long Created { get; set; }
        public string Description { get; set; }
    }
}
