//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corp_Info
    {
        public string About { get; set; }
        public string Contact { get; set; }
        public string Help { get; set; }
        public long Created { get; set; }
        public long Modified { get; set; }
        public int Created_By { get; set; }
        public int Modified_By { get; set; }
        public bool IsCurrent { get; set; }
    }
}
