//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public int User_ID { get; set; }
        public string Department { get; set; }
        public string Name { get; set; }
        public string Duty { get; set; }
        public string Gendar { get; set; }
        public Nullable<long> BirthDate { get; set; }
        public Nullable<long> HireDate { get; set; }
        public Nullable<long> MatureDate { get; set; }
        public string IdentityCard { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
