//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enter_Stock
    {
        public int Enter_Stock_ID { get; set; }
        public long Enter_Date { get; set; }
        public int Shop_ID { get; set; }
        public int StoreHouse_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Buy_ID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
