//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Express_Shop
    {
        public int Express_ID { get; set; }
        public int Shop_ID { get; set; }
        public int IsDefault { get; set; }
        public int Created { get; set; }
        public int Created_By { get; set; }
        public int Modified { get; set; }
        public int Modified_By { get; set; }
    }
}
