//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Stock
    {
        public int Leave_Stock_ID { get; set; }
        public long Leave_Date { get; set; }
        public int Shop_ID { get; set; }
        public int StoreHouse_ID { get; set; }
        public int To_StoreHouse_ID { get; set; }
        public int Sale_ID { get; set; }
    }
}
