//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Stock
    {
        public long Leave_Stock_ID { get; set; }
        public long Leave_Date { get; set; }
        public long Shop_ID { get; set; }
        public long StoreHouse_ID { get; set; }
        public long To_StoreHouse_ID { get; set; }
        public long Sale_ID { get; set; }
    }
}
