//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall_Product
    {
        public string Mall_ID { get; set; }
        public int Outer_ID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<long> Created { get; set; }
        public Nullable<long> Synced { get; set; }
        public int Shop_ID { get; set; }
        public string PicUrl { get; set; }
        public Nullable<long> Modified { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<long> FirstSync { get; set; }
        public Nullable<bool> CreatedProduct { get; set; }
    }
}
