//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall_Product
    {
        public string Mall_ID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> Created { get; set; }
        public Nullable<int> Synced { get; set; }
        public Nullable<int> Shop_ID { get; set; }
        public int Outer_ID { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> Modified { get; set; }
    }
}
