//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Open_Key
    {
        public int ID { get; set; }
        public int Mall_Type_ID { get; set; }
        public string AppKey { get; set; }
        public string AppSecret { get; set; }
        public string Auth_Main_Url { get; set; }
        public string API_Main_Url { get; set; }
        public string CallBack_Url { get; set; }
    }
}
