//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Class
    {
        public int Product_Class_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Order { get; set; }
        public long Create_Time { get; set; }
        public int Create_User_ID { get; set; }
        public int Shop_ID { get; set; }
        public bool Enabled { get; set; }
        public string Mall_CID { get; set; }
        public string Mall_PCID { get; set; }
    }
}
