//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Unit
    {
        public int Product_Unit_ID { get; set; }
        public string Name { get; set; }
        public int User_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Shop_ID { get; set; }
        public long Create_Time { get; set; }
    }
}
