//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Class
    {
        public long Product_Class_ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Parent_ID { get; set; }
        public Nullable<byte> Order { get; set; }
        public Nullable<long> Create_Time { get; set; }
        public Nullable<long> Create_User_ID { get; set; }
        public long Shop_ID { get; set; }
    }
}
