//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Specifications
    {
        public int Product_ID { get; set; }
        public int Product_Spec_Value_ID { get; set; }
        public int Product_Spec_ID { get; set; }
        public Nullable<int> Created { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
