//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_ID { get; set; }
        public int Product_Class_ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int User_ID { get; set; }
        public long Create_Time { get; set; }
        public int Product_Unit_ID { get; set; }
        public int Shop_ID { get; set; }
        public int Parent_ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Update_Time { get; set; }
        public Nullable<int> Update_User_ID { get; set; }
    }
}
