//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long Sale_ID { get; set; }
        public long Sale_Time { get; set; }
        public long Shop_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string Mall_Trade_ID { get; set; }
        public decimal Amount { get; set; }
        public string Express_Cop { get; set; }
        public long Province_ID { get; set; }
    }
}
