//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_SyncTime
    {
        public int ShopID { get; set; }
        public int FirstSyncTime { get; set; }
        public int LastSyncTime { get; set; }
        public int SyncUser { get; set; }
    }
}
