//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Detail
    {
        public int Sale_DID { get; set; }
        public int Sale_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Mall_PID { get; set; }
        public string Mall_Order_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<short> StockStatus { get; set; }
    }
}
