//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Child_Request
    {
        public int ID { get; set; }
        public int Shop_ID { get; set; }
        public int User_ID { get; set; }
        public int Request_Time { get; set; }
        public string Status { get; set; }
        public Nullable<int> Approve_Time { get; set; }
        public Nullable<int> Approve_User_ID { get; set; }
        public int Child_Shop_ID { get; set; }
    }
}
