//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Pile
    {
        public int StockPile_ID { get; set; }
        public int Shop_ID { get; set; }
        public int StockHouse_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<long> First_Enter_Time { get; set; }
        public Nullable<long> LastLeave_Time { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    }
}
