//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Batch
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public int ProductID { get; set; }
        public int ParentProductID { get; set; }
        public long Created { get; set; }
        public int Created_By { get; set; }
        public int ShopID { get; set; }
        public string Desc { get; set; }
    }
}
