//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_House
    {
        public int StoreHouse_ID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public long Create_Time { get; set; }
        public int User_ID { get; set; }
        public int Shop_ID { get; set; }
        public Nullable<int> Guard { get; set; }
        public string Title { get; set; }
    }
}
