//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Action
    {
        public int ID { get; set; }
        public int Action_ID { get; set; }
        public string Action_Name { get; set; }
        public string Action_Description { get; set; }
        public long Created { get; set; }
    }
}
