//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.JXC.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long User_ID { get; set; }
        public string Mall_ID { get; set; }
        public string Mall_Name { get; set; }
        public long Mall_Type { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Parent_User_ID { get; set; }
        public string Parent_Mall_ID { get; set; }
        public string Parent_Mall_Name { get; set; }
    }
}
