//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_route
    {
        public int Id { get; set; }
        public int User_id { get; set; }
        public int Resource_Id { get; set; }
        public int Resource_taocan_id { get; set; }
        public float Sale_price { get; set; }
        public float Purchase_price { get; set; }
        public long Create_time { get; set; }
        public bool Enabled { get; set; }
        public int CreatedBy { get; set; }
        public long Update_time { get; set; }
        public int UpdatedBy { get; set; }
        public float Discount { get; set; }
    }
}
