//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> OpenType { get; set; }
        public long CreatedTime { get; set; }
        public string Name { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPeople { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public string Description { get; set; }
        public float RemainingAmount { get; set; }
        public float CreditAmount { get; set; }
        public string Token { get; set; }
    }
}
