//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help_Info
    {
        public int Id { get; set; }
        public string About { get; set; }
        public string Contact { get; set; }
        public string AgentHelp { get; set; }
        public string AdminHelp { get; set; }
        public int UpdateUser { get; set; }
        public bool IsCurrent { get; set; }
        public long UpdateTime { get; set; }
    }
}
