//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Orders
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public float PlatformSalePrice { get; set; }
        public float PlatformPurchasePrice { get; set; }
        public float AgentSalePrice { get; set; }
        public float AgentPurchasePrice { get; set; }
        public long CreatedTime { get; set; }
        public long StartTime { get; set; }
        public long ExpiredTime { get; set; }
        public long UsedTime { get; set; }
        public bool Used { get; set; }
        public string PhoneNumber { get; set; }
        public string MacAddress { get; set; }
    }
}
