//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Activity_Taocan
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int ResourceId { get; set; }
        public int ResourceTaocanId { get; set; }
        public int RouteId { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public long CreatedTime { get; set; }
        public bool Generated { get; set; }
    }
}
