//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_history
    {
        public int Id { get; set; }
        public float Amount { get; set; }
        public long Pay_time { get; set; }
        public int User_id { get; set; }
        public int Tranfser_Type { get; set; }
        public int ChargeOrderId { get; set; }
        public string PaymentAccount { get; set; }
        public int PayType { get; set; }
        public long CreatedTime { get; set; }
        public string PaymentTradeId { get; set; }
    }
}
