//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resrouce_interface
    {
        public int Id { get; set; }
        public int Resource_id { get; set; }
        public string Username { get; set; }
        public string Userpassword { get; set; }
        public string Interface_classname { get; set; }
        public string Interface_assemblyname { get; set; }
    }
}
