//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMBit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public long Regtime { get; set; }
        public string Description { get; set; }
        public long Update_time { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public sbyte Pay_type { get; set; }
        public float Remaining_amount { get; set; }
        public float Credit_amount { get; set; }
        public Nullable<int> Province_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
    }
}
